### PR TITLE
improve has_import auto-messaging

### LINKED ISSUE #301: Improve has_import auto-messages
We can do a much better job.

### PR DESCRIPTION
**Pull request by filipsch**
- Refer to alias when the alias is not correct
- Convert tests for has_import to use pytest
- Explicit messaging tests in tests/test_messages.py

Fixes #301 

@sumedh10 let me know if anything in here sounds completely ridiculous; otherwise I'll merge in!

### CODE REVIEW

**Comment by sumedh10** [comment]
@filipsch Based on [this](https://github.com/datacamp/pythonwhat/pull/311/files#diff-5f150b7b2a2581087b6bad94008d0ce3R237) line, I was expecting the following scenario to generate the message "Did you import `pandas`?"

```{python}
# Solution code
import pandas as pd

# Student code
import numpy as np
```

However, when I ran this code locally, I get "'pandas' not in solution imports"

Did I misunderstand the PR or do you think I am running an old version?

**Comment by filipsch** [comment]
@sumedh10 Can you give me the exact code that generated this?

**Comment by sumedh10** [comment]
@filipsch 

```{python}
# Version: 2.13.1
from pythonwhat.local import setup_state
s = setup_state(stu_code = 'import pandas as pa', sol_code = 'import numpy')

s.has_import('pandas')
```

> NameError: The package you specified is not in the solution imports itself. 'pandas' not in solution imports

**Comment by filipsch** [comment]
@sumedh10 so it's all good, right :) Cool to see somebody use `setup_state()`!

**Comment by sumedh10** [comment]
@filipsch Yep, all is well! I was confused because in `testwhat`, `sol_code` is the first argument and not `stu_code`.

**Pull request merged**
